name: CI - Code styles, unit tests
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.head_ref }}-codestyles
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: |
          npm ci
          (cd ./packages/block-avatar;pwd;npm ci)
          (cd ./packages/block-button;pwd;npm ci)
          (cd ./packages/block-divider;pwd;npm ci)
          (cd ./packages/block-heading;pwd;npm ci)
          (cd ./packages/block-html;pwd;npm ci)
          (cd ./packages/block-image;pwd;npm ci)
          (cd ./packages/block-spacer;pwd;npm ci)
          (cd ./packages/block-text;pwd;npm ci)
          (cd ./packages/document-core;pwd;npm ci)
          (cd ./packages/editor-sample;pwd;npm ci)
          (cd ./packages/email-builder;pwd;npm ci)
      - run: npx eslint .
      - run: npx prettier . --check
      - run: npm test
      - run: ./node_modules/.bin/tsc --noEmit
