name: CI - Code styles, unit tests
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.head_ref }}-codestyles
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx eslint .
      - run: npx prettier . --check
      - run: npm test
